---
- name: Install Development Environment
  hosts: localhost
  connection: local
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    username: "{{ lookup('env', 'USER') }}"

  # pre_tasks:
  #   - name: Update cache
  #     become: true
  #     ansible.builtin.apt:
  #       force_apt_get: true
  #       update-cache: true
  #       state: present
  #     tags:
  #       - always

  tasks:
    - ansible.builtin.include_tasks: tasks/core.yml

    - name: Zsh
      ansible.builtin.include_tasks: tasks/zsh.yml
      tags: ['zsh']

    # - name: Fzf
    #   ansible.builtin.include_tasks: tasks/fzf.yml
    #   tags: ['fzf']

    # - name: Tmux
    #   ansible.builtin.include_tasks: tasks/tmux.yml
    #   tags: ['tmux']

    # - name: Nvim
    #   ansible.builtin.include_tasks: tasks/nvim.yml
    #   tags: ['nvim']
    #
    # - name: Node
    #   ansible.builtin.include_tasks: tasks/node.yml
    #   tags: ['node']

    # - name: Docker
    #   ansible.builtin.include_tasks: tasks/docker.yml
    #   tags: ['docker']
    #
    # - name: Python
    #   ansible.builtin.include_tasks: tasks/python.yml
    #   tags: ['python']
    #
    # - name: Gnome
    #   ansible.builtin.include_tasks: tasks/gnome.yml
    #   tags: ['gnome']
    #
    # - name: Kitty
    #   ansible.builtin.include_tasks: tasks/kitty.yml
    #   tags: ['kitty']
    #
    # - name: Spotify
    #   ansible.builtin.include_tasks: tasks/spotify.yml
    #   tags: ['spotify']
    #
    # - name: Gimp
    #   ansible.builtin.include_tasks: tasks/gimp.yml
    #   tags: ['gimp']
    #
    # - name: I3
    #   ansible.builtin.include_tasks: tasks/i3.yml
    #   tags: ['i3']
    #
    # - name: Git
    #   ansible.builtin.include_tasks: tasks/git.yml
    #   tags: ['git']
    #
    # - name: K8s
    #   ansible.builtin.include_tasks: tasks/k8s.yml
    #   tags: ['k8s']

    - name: Dotfiles
      ansible.builtin.include_tasks: tasks/dotfiles.yml
      tags: ['dotfiles']
